language: php

matrix:
    include:
        - php: 7.2
        - php: 7.3
          env: STATIC_ANAL=true
#        - php: 7.3
#          env: CRAWL_FLAGS="--usa"
#        - php: 7.3
#          env: CRAWL_FLAGS="--non-usa"

before_install:
    # configure timezone: https://stackoverflow.com/a/27052708/1348344
    - date
    - export TZ=Europe/Prague
    - date

install:
    - composer update

script:
    - vendor/bin/phpunit

    # run from time to time
    - if [[ $CRAWL_FLAGS != "" ]]; then bin/console crawl $CRAWL_FLAGS; fi

    # code analysis
    - if [[ $STATIC_ANAL == true ]]; then composer check-cs; fi
    - if [[ $STATIC_ANAL == true ]]; then composer phpstan; fi

    # make sure there are no duplicates
    - bin/console validate-groups

    # import data
    - bin/console import-meetup-com -vvv
    - bin/console import-dou-ua -vvv
    - bin/console import-crossweb-pl -vvv

    # generate website to "/output" directory, it will be deployed later in "deploy" + imports groups and meetups
    - vendor/bin/statie generate source -vvv

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email:
        on_success: never
