language: php

php: 7.2

before_install:
    # configure timezone: https://stackoverflow.com/a/27052708/1348344
    - date
    - export TZ=Europe/Prague
    - date

install:
    - composer update

script:
    - vendor/bin/phpunit

    # run from time to time
    # - bin/console crawl

    # code analysis
    - composer check-cs
    - composer phpstan

    # make sure there are no duplicates
    - bin/console validate-groups

    # import data
    - bin/console import -vvv

    # generate website to "/output" directory, it will be deployed later in "deploy" + imports groups and meetups
    - vendor/bin/statie generate source -vvv

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email:
        on_success: never
