parameters:
    # id of map element for javascript
    map_id: 'mapid'

    groups_storage: '%kernel.project_dir%/source/_data/groups.yml'
    imported_meetups_storage: '%kernel.project_dir%/source/_data/generated/imported_meetups.yml'

    # setup here: https://secure.meetup.com/meetup_api/key/
    meetup_com_api_key: '3862c18323629314e5c596422581378'

    # how many days into the future the meetups should be imported
    max_forecast_days: 30

    # default empty value
    areas: []
